apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ao-min-side-microfrontend
  namespace: dab
  labels:
    team: dab
spec:
  env:
    - name: CORS_ALLOWED_ORIGIN
      value: "https://www.intern.dev.nav.no"
  image: {{ image }}
  port: 8080
#  liveness:
#    path: ao-min-side-microfrontend/internal/isAlive
#    initialDelay: 10
#  readiness:
#    path: ao-min-side-microfrontend/internal/isReady
#    initialDelay: 10
#  prometheus:
#    enabled: true
#    path: ao-min-side-microfrontend/internal/metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://www.intern.dev.nav.no/dab/ao-min-side-microfrontend"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: veilarboppfolging
          namespace: poao